modLoader = "klf"
loaderVersion = "[1,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/Tonywww2"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Tonywww"
description = '''
A blackboard block that renders a question; answer in chat to win rewards.
'''

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"
